### ISSUE TITLE
Cant Translate SKİP and DONE Button

### ISSUE THREAD

**Issue by serkandyck** [vlonjatg/AppTour#1]
Can Translate overiding on string.xml AppIntro
string name="skip_button">Geç</string>
string name="done_button">Bitir</string>

But not effect

**Comment by vlonjat-gashi** [comment]
@asdstyle33 you can use:

```
//Set String value of the Skip button
setSkipText("Geç");

//Set String value of the Done button
setDoneText("Bitir");
```

Place them in the `init` method.

**Comment by serkandyck** [comment]
ahh my fault sorry

**Comment by vlonjat-gashi** [comment]
@asdstyle33 no worries.
