### ISSUE TITLE
button click

### ISSUE THREAD

**Issue by Msentri** [vlonjatg/AppTour#2]
hi i would like to know how do you handle a button click ?

**Comment by vlonjat-gashi** [comment]
@Msentri, you can use the methods below to handle Skip and Done buttons. For more check the sample app!

```
@Override
public void onSkipPressed() {
        //Do something after clicking Skip button.
}

@Override
public void onDonePressed() {
    //Do something after clicking Done button.
}
```

**Comment by Msentri** [comment]
Thanks works well....much appreciated. :)
